apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: kubegems
  name: kubegems

---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: global
  namespace: kubegems-installer
  annotations:
    plugins.kubegems.io/category: core/KubeGems
    plugins.kubegems.io/description: KubeGems global values.
spec:
  kind: template
  url: https://charts.kubegems.io/kubegems
  chart: global
  version: "1.0.0"
  values:
    clusterName: "manager-cluster"
    imageRegistry: docker.io
    imageRepository: "kubegems"
    storageClass: local-hostpath 
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
  namespace: kubegems-installer
  annotations:
    plugins.kubegems.io/category: core/KubeGems
    plugins.kubegems.io/description: KubeGems core service and dashboard.
spec:
  kind: helm
  url: https://charts.kubegems.io/kubegems
  installNamespace: kubegems
  version: 1.23.2
  valuesFrom:
    - kind: ConfigMap
      name: "kubegems-global-values"
      prefix: "global."
  values:
    dashboard:
      service:
        type: NodePort